# Catppuccin Mocha soft pastel cards
background-color=#1E1E2EF2
text-color=#CDD6F4FF
border-color=#F38BA8FF
progress-color=over #89B4FACC

[hidden]
format=<span weight="bold">%h more notifications</span> (%t total)
background-color=#313244FF
text-color=#CDD6F4FF
border-color=#74C7ECFF

[urgency=low]
background-color=#313244EA
text-color=#BAC2DEFF
border-color=#A6E3A1FF
default-timeout=5000

[urgency=normal]
background-color=#1E1E2EF2
text-color=#CDD6F4FF
border-color=#F38BA8FF

[urgency=critical]
background-color=#45475AFA
text-color=#F5E0DCFF
border-color=#F38BA8FF
default-timeout=0
group-by=

[app-name="Spotify"]
border-color=#A6E3A1FF

[app-name="firefox"]
border-color=#FAB387FF
