# Everforest Light warm paper cards
background-color=#F3EAD3F2
text-color=#3C4841FF
border-color=#E67E80FF
progress-color=over #7FBBB3CC

[hidden]
format=<span weight="bold">%h more notifications</span> (%t total)
background-color=#EAE4D0FF
text-color=#3C4841FF
border-color=#7FBBB3FF

[urgency=low]
background-color=#EAE4D0EA
text-color=#56635FFF
border-color=#A7C080FF
default-timeout=5000

[urgency=normal]
background-color=#F3EAD3F2
text-color=#3C4841FF
border-color=#E67E80FF

[urgency=critical]
background-color=#E6D8B5FA
text-color=#2F3833FF
border-color=#E67E80FF
default-timeout=0
group-by=

[app-name="Spotify"]
border-color=#7FBBB3FF

[app-name="firefox"]
border-color=#DBBC7FFF
