# Gruvbox modern notification cards
background-color=#1D2021E6
text-color=#D4BE98FF
border-color=#EA6962FF
progress-color=over #7DAEA3CC
format=<span foreground="#7DAEA3FF" weight="bold" size="large">%s</span>\n\n<span foreground="#D4BE98FF" size="medium">%b</span>

[hidden]
format=<span foreground="#7DAEA3FF" weight="bold">%h more notifications</span> <span foreground="#D4BE98FF">(%t total)</span>
background-color=#1D2021E6
text-color=#D4BE98FF
border-color=#7DAEA3FF

[urgency=low]
background-color=#1D2021E6
text-color=#BDAE93FF
border-color=#89B482FF
default-timeout=5000
format=<span foreground="#7DAEA3FF" weight="bold" size="large">%s</span>\n\n<span foreground="#BDAE93FF" size="medium">%b</span>

[urgency=normal]
background-color=#1D2021E6
text-color=#D4BE98FF
border-color=#EA6962FF
format=<span foreground="#7DAEA3FF" weight="bold" size="large">%s</span>\n\n<span foreground="#D4BE98FF" size="medium">%b</span>

[urgency=critical]
background-color=#1D2021E6
text-color=#FBF1C7FF
border-color=#EA6962FF
default-timeout=0
group-by=
format=<span foreground="#7DAEA3FF" weight="bold" size="large">%s</span>\n\n<span foreground="#FBF1C7FF" size="medium">%b</span>

[app-name="Spotify"]
border-color=#7DAEA3FF
format=<span foreground="#7DAEA3FF" weight="bold">%s</span>\n\n<span foreground="#D4BE98FF">%b</span>

[app-name="firefox"]
border-color=#D8A657FF
format=<span foreground="#7DAEA3FF" weight="bold" size="large">%s</span>\n\n<span foreground="#D4BE98FF" size="medium">%b</span>
