# Nord cool slate cards
background-color=#2E3440F2
text-color=#ECEFF4FF
border-color=#88C0D0FF
progress-color=over #81A1C1CC

[hidden]
format=<span weight="bold">%h more notifications</span> (%t total)
background-color=#3B4252FF
text-color=#E5E9F0FF
border-color=#81A1C1FF

[urgency=low]
background-color=#3B4252EA
text-color=#D8DEE9FF
border-color=#A3BE8CFF
default-timeout=5000

[urgency=normal]
background-color=#2E3440F2
text-color=#ECEFF4FF
border-color=#88C0D0FF

[urgency=critical]
background-color=#434C5EFA
text-color=#FFFFFFFF
border-color=#BF616AFF
default-timeout=0
group-by=

[app-name="Spotify"]
border-color=#A3BE8CFF

[app-name="firefox"]
border-color=#EBCB8BFF
