font=VictorMono Nerd Font 11

width=360
height=140
outer-margin=16,20,0,0
margin=12
padding=30,34

border-size=1
border-radius=8
icon-border-radius=6

icons=1
max-icon-size=48
icon-location=left

markup=true
actions=true
history=true
max-history=20
sort=-time
group-by=app-name,summary
max-visible=4

format=<span weight="bold" size="large">%s</span>\n<span size="medium">%b</span>
text-alignment=left

default-timeout=8000
ignore-timeout=0

anchor=top-right
layer=overlay

on-button-left=invoke-default-action
on-button-right=dismiss
on-button-middle=dismiss-group

[grouped]
format=<span weight="bold">(%g)</span> %s\n%b
invisible=1

[group-index=0]
invisible=0

[app-name="Spotify"]
format=<span weight="bold">%s</span>\n%b
